# Generated by Django 4.2.26 on 2025-11-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-created_at']},
        ),
    ]
