# Generated by Django 4.2.26 on 2025-12-02 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary_entries', '0003_contactemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
