# Generated by Django 4.2.26 on 2025-12-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_entries', '0004_contactemail_created_at_contactemail_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about your condition and wellbeing (max 1000 characters)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='triggers',
            field=models.TextField(blank=True, help_text='Describe any triggers that may have affected your pain (max 300 characters)', max_length=500, null=True),
        ),
    ]
