# Generated by Django 4.2.26 on 2025-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_entries', '0005_alter_diaryentry_location_alter_diaryentry_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='triggers',
            field=models.TextField(blank=True, help_text='Describe any triggers that may have affected your pain (max 300 characters)', max_length=300, null=True),
        ),
    ]
