# Generated by Django 4.2.26 on 2025-12-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_entries', '0006_alter_diaryentry_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
